# Generated by Django 4.0.2 on 2022-02-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('unit_num', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('mileage', models.IntegerField()),
                ('manufacturer', models.CharField(choices=[('Ford', 'Ford'), ('GMC', 'GMC'), ('TESLA', 'TESLA')], max_length=5)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inoperative', 'Inoperative'), ('Inactive', 'Inactive')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mileage_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mileage', models.IntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', related_query_name='history', to='vehicleApi.vehicle')),
            ],
            options={
                'verbose_name': 'history',
                'ordering': ('date',),
            },
        ),
    ]
